//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kkurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credits
    {
        public int ID_credita { get; set; }
        public int ID_klienta { get; set; }
        public int Sum_Credita { get; set; }
        public string Procent_credita { get; set; }
        public string Date_Oformleniya { get; set; }
        public int ID__sotrudnika { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
